---
- hosts: localhost
  connection: local
  gather_facts: False 

  tasks:
  - name: install the latest version of Apache
    yum: name=httpd state=latest
   
  - name: Enable the service
    service: name=httpd state=start
    
  - name: Enalbe on boot
    service: name=httpd enabled=yes
